# Generated by Django 4.1.7 on 2023-03-13 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_rename_ползователи_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('date', models.DateTimeField(verbose_name='Дата регистраций')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ползователи',
        ),
    ]
