# Generated by Django 4.1.7 on 2023-03-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userprofile_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', error_messages={'invalid': 'Invalid email format', 'required': 'Email is required'}, max_length=50, verbose_name='Password'),
        ),
    ]
